'use client'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'
import { useState } from 'react'
import { Search, MapPinned } from 'lucide-react'

export default function TrackPage(){
 const [id,setId]=useState('');const [phone,setPhone]=useState('');const [result,setResult]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 async function track(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');setResult(null);const s=createClient();const {data,error}=await s.rpc('track_application',{p_application_no:id,p_phone:phone});if(error)setError(error.message);else if(!data?.length)setError('Application ID ও মোবাইল নম্বর মিলিয়ে কোনো আবেদন পাওয়া যায়নি।');else setResult(data[0]);setLoading(false)}
 return <div className="auth-shell"><div style={{width:'min(700px,100%)'}}><Link href="/" style={{display:'inline-flex',alignItems:'center',gap:8,color:'var(--brand)',fontWeight:700,marginBottom:15}}><MapPinned size={18}/> E-Vumi Seba</Link><div className="card" style={{padding:30}}><span className="badge badge-teal">Application Tracking</span><h1 style={{fontSize:30,marginTop:8}}>আবেদনের অবস্থা দেখুন</h1><p className="muted">Application ID এবং নিবন্ধিত মোবাইল নম্বর দিয়ে সীমিত status তথ্য দেখুন।</p><form onSubmit={track} style={{marginTop:22}}><div className="form-group"><label className="label">Application ID</label><input className="input" required placeholder="EVS-2026-000001" value={id} onChange={e=>setId(e.target.value)}/></div><div className="form-group"><label className="label">নিবন্ধিত মোবাইল</label><input className="input" required value={phone} onChange={e=>setPhone(e.target.value)}/></div><button className="btn btn-primary" style={{width:'100%'}} disabled={loading}><Search size={17}/>{loading?'খোঁজা হচ্ছে...':'ট্র্যাক করুন'}</button></form>{error&&<p className="error" style={{marginTop:14}}>{error}</p>}{result&&<div className="card" style={{padding:22,marginTop:22,background:'#f8fffd'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><p className="muted" style={{fontSize:12}}>Application ID</p><h3>{result.application_no}</h3></div><span className="badge badge-teal">{result.status}</span></div><h4 style={{marginTop:20}}>{result.service_name}</h4><p className="muted" style={{fontSize:13,marginTop:7}}>সর্বশেষ আপডেট: {new Date(result.updated_at).toLocaleString('bn-BD')}</p></div>}</div></div></div>
}
