'use client'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'
import { useState } from 'react'
import { UserPlus, MapPinned } from 'lucide-react'
import { useRouter } from 'next/navigation'

export default function RegisterPage(){
 const router=useRouter();const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState('customer');const [error,setError]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');setMessage('');const supabase=createClient();const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,phone,role:role==='agent'?'agent':'customer'}}});if(error)setError(error.message);else if(data.session)router.push('/dashboard');else setMessage('রেজিস্ট্রেশন সফল। ইমেইল verification সম্পন্ন করে লগইন করুন।');setLoading(false)}
 return <div className="auth-shell"><div className="auth-card card"><div style={{textAlign:'center',marginBottom:20}}><div style={{height:48,width:48,borderRadius:14,background:'var(--brand)',color:'#fff',display:'grid',placeItems:'center',margin:'0 auto 10px'}}><MapPinned/></div><h1>রেজিস্টার</h1><p className="muted">নতুন E-Vumi Seba account তৈরি করুন</p></div><form onSubmit={submit}><div className="form-group"><label className="label">পূর্ণ নাম</label><input className="input" required value={name} onChange={e=>setName(e.target.value)}/></div><div className="form-group"><label className="label">মোবাইল</label><input className="input" required value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="form-group"><label className="label">ইমেইল</label><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="form-group"><label className="label">Account type</label><select className="select" value={role} onChange={e=>setRole(e.target.value)}><option value="customer">Customer</option><option value="agent">Agent</option></select></div><div className="form-group"><label className="label">পাসওয়ার্ড</label><input className="input" type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></div>{error&&<p className="error" style={{marginBottom:14}}>{error}</p>}{message&&<p className="success" style={{marginBottom:14}}>{message}</p>}<button className="btn btn-primary" style={{width:'100%'}} disabled={loading}><UserPlus size={17}/>{loading?'অপেক্ষা করুন...':'অ্যাকাউন্ট তৈরি করুন'}</button></form><p style={{textAlign:'center',marginTop:18,fontSize:14}}>আগে account আছে? <Link href="/auth/login" style={{color:'var(--brand)',fontWeight:700}}>লগইন</Link></p></div></div>
}
