'use client'
import { createClient } from '@/lib/supabase/client'
import { useEffect,useState } from 'react'
import { useRouter,useSearchParams } from 'next/navigation'

export default function NewApplication(){
 const router=useRouter();const params=useSearchParams();const [services,setServices]=useState<any[]>([]);const [serviceId,setServiceId]=useState('');const [name,setName]=useState('');const [phone,setPhone]=useState('');const [district,setDistrict]=useState('');const [upazila,setUpazila]=useState('');const [mouza,setMouza]=useState('');const [khatian,setKhatian]=useState('');const [dag,setDag]=useState('');const [area,setArea]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false)
 useEffect(()=>{(async()=>{const s=createClient();const {data}=await s.from('services').select('*').eq('active',true).order('name_bn');setServices(data||[]);const wanted=params.get('service');if(wanted){const match=(data||[]).find((x:any)=>x.slug===wanted||x.name_bn.includes(wanted));if(match)setServiceId(match.id)}})()},[params])
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push('/auth/login');return}const service=services.find(x=>x.id===serviceId);if(!service){setError('সেবা নির্বাচন করুন');setLoading(false);return}const {data:profile}=await s.from('profiles').select('role').eq('id',user.id).single();const payload:any={customer_id:profile?.role==='customer'?user.id:user.id,agent_id:profile?.role==='agent'?user.id:null,service_id:serviceId,applicant_name:name,applicant_phone:phone,district,upazila,mouza,khatian_no:khatian,dag_no:dag,land_area:area,official_fee:service.official_fee,other_cost:service.other_cost,service_fee:service.service_fee,agent_commission:profile?.role==='agent'?service.agent_commission:0};const {data,error}=await s.from('applications').insert(payload).select('id').single();if(error)setError(error.message);else router.push(`/dashboard/applications/${data.id}`);setLoading(false)}
 return <div><div className="page-head"><div><h1 style={{fontSize:28}}>নতুন আবেদন</h1><p className="muted">আবেদনকারী ও জমির প্রাথমিক তথ্য দিন</p></div></div><form onSubmit={submit} className="card" style={{padding:24,maxWidth:900}}><div className="grid-2"><div className="form-group"><label className="label">সেবা *</label><select className="select" required value={serviceId} onChange={e=>setServiceId(e.target.value)}><option value="">সেবা নির্বাচন করুন</option>{services.map(s=><option value={s.id} key={s.id}>{s.name_bn}</option>)}</select></div><div className="form-group"><label className="label">আবেদনকারীর নাম *</label><input className="input" required value={name} onChange={e=>setName(e.target.value)}/></div><div className="form-group"><label className="label">মোবাইল *</label><input className="input" required value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="form-group"><label className="label">জেলা</label><input className="input" value={district} onChange={e=>setDistrict(e.target.value)}/></div><div className="form-group"><label className="label">উপজেলা</label><input className="input" value={upazila} onChange={e=>setUpazila(e.target.value)}/></div><div className="form-group"><label className="label">মৌজা</label><input className="input" value={mouza} onChange={e=>setMouza(e.target.value)}/></div><div className="form-group"><label className="label">খতিয়ান নম্বর</label><input className="input" value={khatian} onChange={e=>setKhatian(e.target.value)}/></div><div className="form-group"><label className="label">দাগ নম্বর</label><input className="input" value={dag} onChange={e=>setDag(e.target.value)}/></div><div className="form-group"><label className="label">জমির পরিমাণ</label><input className="input" value={area} onChange={e=>setArea(e.target.value)}/></div></div>{serviceId&&(()=>{const x=services.find(s=>s.id===serviceId);return x?<div className="card" style={{padding:16,margin:'4px 0 18px',background:'#f8fffd'}}><b>ফি breakdown</b><div className="grid-2" style={{marginTop:10,fontSize:14}}><span>Official fee: ৳{x.official_fee}</span><span>Other cost: ৳{x.other_cost}</span><span>E-Vumi service fee: ৳{x.service_fee}</span><span>Agent commission: ৳{x.agent_commission}</span></div></div>:null})()} {error&&<p className="error" style={{marginBottom:14}}>{error}</p>}<button className="btn btn-primary" disabled={loading}>{loading?'আবেদন তৈরি হচ্ছে...':'আবেদন তৈরি করুন'}</button></form></div>
}
