import { createClient } from '@/lib/supabase/server'
import Link from 'next/link'
import { ArrowRight, Clock3, FilePlus2, Users, WalletCards } from 'lucide-react'

export default async function DashboardPage(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();
 const {data:profile}=await supabase.from('profiles').select('role,full_name').eq('id',user!.id).single();
 let query=supabase.from('applications').select('id,application_no,applicant_name,status,customer_total,created_at,services(name_bn)',{count:'exact'}).order('created_at',{ascending:false}).limit(8)
 if(profile?.role==='agent')query=query.eq('agent_id',user!.id);else if(profile?.role==='customer')query=query.eq('customer_id',user!.id)
 const {data:apps,count}=await query
 const {count:processing}=profile?.role==='agent'?await supabase.from('applications').select('*',{count:'exact',head:true}).eq('agent_id',user!.id).eq('status','PROCESSING'):profile?.role==='customer'?await supabase.from('applications').select('*',{count:'exact',head:true}).eq('customer_id',user!.id).eq('status','PROCESSING'):await supabase.from('applications').select('*',{count:'exact',head:true}).eq('status','PROCESSING')
 const {count:customers}=profile?.role==='agent'?await supabase.from('applications').select('customer_id',{count:'exact',head:true}).eq('agent_id',user!.id):{count:null}
 return <><div className="page-head"><div><p className="muted">{profile?.role==='agent'?'Agent Dashboard':profile?.role==='customer'?'Customer Dashboard':'Operations Dashboard'}</p><h1 style={{fontSize:28}}>আসসালামু আলাইকুম, {profile?.full_name||'User'}</h1></div><Link href="/dashboard/applications/new" className="btn btn-primary"><FilePlus2 size={17}/> নতুন আবেদন</Link></div>
 <div className="grid-4"><div className="card stat"><FilePlus2 color="var(--brand)"/><p className="muted" style={{fontSize:13,marginTop:10}}>মোট আবেদন</p><div className="stat-number">{count||0}</div></div><div className="card stat"><Users color="var(--brand)"/><p className="muted" style={{fontSize:13,marginTop:10}}>Customer</p><div className="stat-number">{customers??'—'}</div></div><div className="card stat"><Clock3 color="var(--brand)"/><p className="muted" style={{fontSize:13,marginTop:10}}>Processing</p><div className="stat-number">{processing||0}</div></div><div className="card stat"><WalletCards color="var(--brand)"/><p className="muted" style={{fontSize:13,marginTop:10}}>Role</p><div className="stat-number" style={{fontSize:18}}>{profile?.role}</div></div></div>
 <div className="card" style={{padding:22,marginTop:22}}><div className="page-head" style={{marginBottom:10}}><h2 style={{fontSize:21}}>সাম্প্রতিক আবেদন</h2><Link href="/dashboard/applications" style={{color:'var(--brand)',fontWeight:700}}>সব দেখুন <ArrowRight size={15} style={{verticalAlign:'middle'}}/></Link></div><div className="table-wrap"><table><thead><tr><th>Application</th><th>Customer</th><th>Service</th><th>Status</th><th>Amount</th></tr></thead><tbody>{(apps||[]).map((a:any)=><tr key={a.id}><td><Link href={`/dashboard/applications/${a.id}`} style={{fontWeight:700,color:'var(--brand)'}}>{a.application_no}</Link></td><td>{a.applicant_name}</td><td>{a.services?.name_bn}</td><td><span className="badge badge-teal">{a.status}</span></td><td>৳{Number(a.customer_total||0).toLocaleString('bn-BD')}</td></tr>)}{!apps?.length&&<tr><td colSpan={5} className="muted">এখনও কোনো আবেদন নেই।</td></tr>}</tbody></table></div></div></>
}
